// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZFmVdGUd3n7hRX8vWpvWlp_t4TcUNj0',
    appId: '1:606744934510:web:0ed4cde346f56acec54e7f',
    messagingSenderId: '606744934510',
    projectId: 'dr-tarek-platform',
    authDomain: 'dr-tarek-platform.firebaseapp.com',
    storageBucket: 'dr-tarek-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdHz2ZF9QLsR6dJw56RX0x0MV2pzavXhc',
    appId: '1:606744934510:android:e272d428dbc477bbc54e7f',
    messagingSenderId: '606744934510',
    projectId: 'dr-tarek-platform',
    storageBucket: 'dr-tarek-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBPOaR6KcNN4kH_KQWfGhL0gcQZMp9uQo',
    appId: '1:606744934510:ios:9718f3e90867d668c54e7f',
    messagingSenderId: '606744934510',
    projectId: 'dr-tarek-platform',
    storageBucket: 'dr-tarek-platform.firebasestorage.app',
    iosBundleId: 'com.drtarek.platform',
  );
}
